---
- name: Configure VPS Ubuntu
  hosts: vps
  become: true

  roles:
    - role: setup
      tags: [setup]

    - role: traefik
      tags: [traefik]

    - role: portainer
      tags: [portainer]

    - role: postgres
      tags: [postgres]

    - role: adminer
      tags: [adminer]

    - role: cloudbeaver
      tags: [cloudbeaver]

    - role: minio
      tags: [minio]

    - role: rabbitmq
      tags: [rabbitmq]

    - role: dozzle
      tags: [dozzle]
